server {
    listen 8080 default_server;
    server_name _;
    root /var/www/zabbix;
    index index.php;
    client_max_body_size 16m;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_read_timeout 300;
    }

    location ~ /(\.ht|api/classes|conf|include|locale) {
        deny all;
    }
}
